### ISSUE TITLE
Support-colors feature of owo-colors uses atty which has an alert

### ISSUE THREAD

**Issue by harmless-tech** [cargo-prebuilt/cargo-prebuilt#48]
https://github.com/cargo-prebuilt/cargo-prebuilt/security/dependabot/10

Also bpaf sigh

**Comment by pacak** [comment]
> Also bpaf sigh

FWIW `bpaf` uses `supports-colors` 2.0 which uses `is_terminal` instead of `atty`. I made a PR to `owo-colors` too but it was not properly released yet.
